version: "3"

services:

  front:
    image: abiosoft/caddy
    container_name: "ex_front"
    environment:
      - CADDYPATH=/etc/caddycerts
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.docker/caddy/Caddyfile:/etc/Caddyfile
      - ./.docker/caddy/caddyssl:/etc/caddycerts
      - .:/app
    depends_on:
      - app

  mysql:
    image: mysql:5.7
    container_name: "ex_mysql"
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=laravel"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: ex_app:alpine
    build: ./.docker/app
    container_name: "ex_app"
    volumes:
      - .:/app
    depends_on:
      - mysql

volumes:
  db_data:
